Update lesson
learn-co-curriculum/react-ts-props-basics-lab pull request #1
Opened 2022-09-13 21:14 UTC by jlboba

Changes made: 
- Configured with TS 
- Added instructions for TS specific things (interface, typing props) 

Solution branch available

2022-09-15 19:10 UTC, lizbur10 requested changes
This looks great - everything runs fine.

2022-09-15 19:10 UTC, lizbur10 commented on README.md
> +      <Person name="Salman" age="27">
Change to age={27}

2022-09-16 15:01 UTC, jlboba commented on README.md
> +      <Person name="Salman" age="27">
```suggestion
      <Person name="Salman" age=27>
```

2022-09-16 15:01 UTC, jlboba commented on README.md
> +      <Person name="Salman" age=27>
```suggestion
      <Person name="Salman" age={27}>
```

2022-09-16 15:02 UTC, merged